import Head from "next/head";
import Image from "next/image";
import TableData from "../src/components/TableData";

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>HMS - Pragathi Hospital</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <section>
        <TableData />
      </section>
    </div>
  );
}
